name: Install Files

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run install script
        run: bash new_machine_installation/main.sh
